services:
  sistema:
    build:
      context: ./src/ProjetoComandas
      dockerfile: ProjetoComandas.View/Dockerfile
    ports:
      - 8100:80
      - 1443:443
    depends_on:
      - banco
  banco:
    image: mysql:8.0.31
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_comandas
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senhaFortissima
    ports:
      - 3307:3306      
    volumes:
      - banco_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/
  front:
    build: ./src/ProjetoComandasFront/projeto-comandas
    depends_on:
      - sistema
    ports:
      - 8081:80
volumes:
  banco_data: