DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS COMANDA_EM_USO;
DROP TABLE IF EXISTS COMANDA;
DROP TABLE IF EXISTS CLIENTE_TELEFONE;
DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE CATEGORIA
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL
);

CREATE TABLE PRODUTO
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CATEGORIA INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL,
    PRECO DECIMAL NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL,
    CONSTRAINT FK_PRODUTO_CATEGORIA_ID FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE COMANDA
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    COD_BARRAS VARCHAR(200) NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL    
);

CREATE TABLE CLIENTE
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(20) NOT NULL,
    SOBRENOME VARCHAR(200) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    DT_NASCIMENTO TIMESTAMP NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL
);

CREATE TABLE CLIENTE_TELEFONE
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    NUMERO INT NOT NULL,
    CONSTRAINT FK_CLIENTE_TELEFONE_CLIENTE_ID FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
);

CREATE TABLE COMANDA_EM_USO
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_COMANDA INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    DT_RETIRADA TIMESTAMP NOT NULL,
    DT_DEVOLUCAO TIMESTAMP NULL,
    CONSTRAINT FK_COMANDA_EM_USO_COMANDA_ID FOREIGN KEY (ID_COMANDA) REFERENCES COMANDA(ID)
);

