DROP TABLE IF EXISTS PRODUTO_NA_COMANDA;
DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS COMANDA_EM_USO;
DROP TABLE IF EXISTS COMANDA;
DROP TABLE IF EXISTS CLIENTE_TELEFONE;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF exists PERFIL_ACESSO;
DROP TABLE IF EXISTS ACESSO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF exists PERFIL;

CREATE TABLE CATEGORIA
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL
);

CREATE TABLE PRODUTO
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CATEGORIA INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL,
    PRECO DECIMAL NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL,
    CONSTRAINT FK_PRODUTO_CATEGORIA_ID FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE COMANDA
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    COD_BARRAS VARCHAR(200) NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL    
);

CREATE TABLE CLIENTE
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(20) NOT NULL,
    SOBRENOME VARCHAR(200) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    DT_NASCIMENTO TIMESTAMP NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL
);

CREATE TABLE CLIENTE_TELEFONE
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    NUMERO INT NOT NULL,
    CONSTRAINT FK_CLIENTE_TELEFONE_CLIENTE_ID FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
);

CREATE TABLE COMANDA_EM_USO
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_COMANDA INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    DT_RETIRADA TIMESTAMP NOT NULL,
    DT_DEVOLUCAO TIMESTAMP NULL,
    CONSTRAINT FK_COMANDA_EM_USO_COMANDA_ID FOREIGN KEY (ID_COMANDA) REFERENCES COMANDA(ID)
);



Create Table PRODUTO_NA_COMANDA
(
	ID INT auto_increment primary key,
    ID_COMANDA_EM_USO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    DATA_INCLUSAO timestamp NULL, 
    constraint FK_PRODUTO_NA_COMANDA_ID_COMANDA foreign key (ID_COMANDA_EM_USO) references COMANDA_EM_USO (ID),
    CONSTRAINT FK_PRODUTO_NA_COMANDA_PRODUTO foreign key (ID_PRODUTO) references PRODUTO (ID)
);

create table ACESSO 
(
	ID INT auto_increment PRIMARY KEY,
    NOME varchar(100) NOT NULL,
    DT_CADASTRO timestamp NOT NULL
);
CREATE TABLE PERFIL 
(
	ID INT auto_increment PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DT_CADASTRO timestamp NOT NULL
);

CREATE TABLE PERFIL_ACESSO 
(
	ID INT auto_increment PRIMARY KEY,
    ID_ACESSO INT NOT NULL,
    ID_PERFIL INT NOT NULL,
    CONSTRAINT FK_PERFIL_ACESSO_ACESSO foreign KEY (ID_ACESSO) REFERENCES ACESSO (ID),
	CONSTRAINT FK_PERFIL_ACESSO_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL (ID)
);

CREATE TABLE USUARIO 
(
	ID INT auto_increment primary KEY,
    ID_PERFIL INT NOT NULL,
    USUARIO varchar(100) not null,
    CHAVE VARCHAR(3000) NOT NULL,
    DT_CADASTRO timestamp not null,
    constraint FK_USUARIO_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL (ID)
);
